# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c734be45a397ff5331628ecec3265af12cf03301783e6172a87d4cfd82bb8f6b8a97f3bbb201fc895f425b8d79df0e6cee6e74b3aed1234cb416df2042bf73e8

test:
  secret_key_base: 921a705bbe8f6312738429501d0758de0280d7daeec21fa955b8f61abc4b3eaefc5ad4ffc93694caa5fee714fa877b21b767732e58284f2580b8c09f536679e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
